feat: get version from tag

diff --git a/.github/workflows/pypi-publish-on-release.yml b/.github/workflows/pypi-publish-on-release.yml
--- a/.github/workflows/pypi-publish-on-release.yml
+++ b/.github/workflows/pypi-publish-on-release.yml
@@ -6,6 +6,11 @@ on:
       - published
 
 jobs:
+  call-test-lint:
+    uses: ./.github/workflows/test-lint.yml
+    with:
+      ref: ${{ github.event.release.target_commitish }}
+
   build:
     name: Build distribution 📦
     runs-on: ubuntu-latest
@@ -24,6 +29,20 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install hatch twine
+
+    - name: Validate version
+      run: |
+        version=$(hatch version)
+        if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid version format"
+            exit 0
+        else
+            echo "Invalid version format"
+            exit 1
+        fi
+    - name: Run unit tests
+      run: |
+
 
     - name: Build
       run: |
